# Generated by Django 4.0.3 on 2022-04-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createdby',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='travellocation',
            old_name='createdby',
            new_name='user',
        ),
    ]
