# Generated by Django 4.0.3 on 2022-04-07 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_travellocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellocation',
            name='favorites',
            field=models.ManyToManyField(related_name='location_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
